name: test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12"]
        resolution: ["highest", "lowest-direct"]

    steps:
    - uses: actions/checkout@v2

    - name: Set up uv
      # Install a specific uv version using the installer
      run: curl -LsSf https://astral.sh/uv/0.4.1/install.sh | sh

    - name: Test with pytest
      run: |
        uv sync --resolution ${{ matrix.resolution }} --python ${{ matrix.python-version }} --extra dev
        uv pip install -e .
        uv run pytest --cov --cov-branch --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}